E-Banking System: com.bank.gui.view.panel.AdminCustomerDetailsPanel Class Reference
com.bank.gui.view.panel.AdminCustomerDetailsPanel Class Reference
Εμφανίζει στοιχεία πελάτη (Customer) και τους συνδεδεμένους λογαριασμούς.
Public Member Functions
AdminCustomerDetailsPanel (UserManager userManager, AccountManager accountManager)
Δημιουργεί το panel εμφάνισης στοιχείων πελάτη για τον Admin.
Detailed Description
Εμφανίζει στοιχεία πελάτη (Customer) και τους συνδεδεμένους λογαριασμούς.
Ο διαχειριστής εισάγει το ΑΦΜ του πελάτη, και η φόρμα εμφανίζει:
Πλήρες όνομα, username, VAT και ρόλο.
Όλους τους λογαριασμούς του πελάτη με IBAN και υπόλοιπο.
Αν δεν υπάρχει πελάτης ή λογαριασμοί, εμφανίζονται κατάλληλα μηνύματα.
Ροή:
Εισαγωγή VAT και πάτημα “Search”.
Αναζήτηση πελάτη μέσω UserManager#findByVat(String).
Εμφάνιση όλων των accounts του πελάτη από AccountManager#getAllAccounts().
See also
UserManager
AccountManager
Customer
Constructor & Destructor Documentation
AdminCustomerDetailsPanel()
com.bank.gui.view.panel.AdminCustomerDetailsPanel.AdminCustomerDetailsPanel (UserManager userManager, AccountManager accountManager)
Δημιουργεί το panel εμφάνισης στοιχείων πελάτη για τον Admin.
Parameters
userManager Ο διαχειριστής χρηστών για αναζήτηση με VAT.
accountManager Ο διαχειριστής λογαριασμών για φόρτωση accounts.
References com.bank.manager.UserManager.findByVat(), com.bank.manager.AccountManager.getAllAccounts(), com.bank.model.users.User.getFullName(), com.bank.model.users.User.getRole(), com.bank.model.users.User.getUsername(), and com.bank.model.users.Customer.getVat().
The documentation for this class was generated from the following file:
gui/view/panel/AdminCustomerDetailsPanel.java