E-Banking System: com.bank.gui.view.panel.DepositPanel Class Reference
com.bank.gui.view.panel.DepositPanel Class Reference
Panel για κατάθεση χρημάτων από τον χρήστη σε έναν από τους λογαριασμούς του.
Public Member Functions
DepositPanel (User user, AccountManager accountManager)
Δημιουργεί panel για εκτέλεση κατάθεσης σε έναν από τους λογαριασμούς του χρήστη.
Detailed Description
Panel για κατάθεση χρημάτων από τον χρήστη σε έναν από τους λογαριασμούς του.
Ο χρήστης επιλέγει έναν λογαριασμό από λίστα IBAN, εισάγει ποσό κατάθεσης και εκτελεί τη συναλλαγή Deposit. Το υπόλοιπο ενημερώνεται δυναμικά.
See also
Deposit
TransactionManager
AccountManager
Constructor & Destructor Documentation
DepositPanel()
com.bank.gui.view.panel.DepositPanel.DepositPanel (User user, AccountManager accountManager)
Δημιουργεί panel για εκτέλεση κατάθεσης σε έναν από τους λογαριασμούς του χρήστη.
Parameters
user Ο ενεργός χρήστης.
accountManager Ο διαχειριστής λογαριασμών.
References com.bank.manager.TransactionManager.execute(), com.bank.manager.AccountManager.findByIban(), com.bank.manager.AccountManager.getAllAccounts(), com.bank.model.accounts.Account.getBalance(), and com.bank.model.accounts.Account.getIban().
The documentation for this class was generated from the following file:
gui/view/panel/DepositPanel.java