E-Banking System: com.bank.gui.app.EBankingApp Class Reference
com.bank.gui.app.EBankingApp Class Reference
Swing entry point for the e-banking graphical client.
Static Public Member Functions
static void main (String[] args)
Application entry point (Swing).
Detailed Description
Swing entry point for the e-banking graphical client.
Bootstraps the application on the Swing Event Dispatch Thread (EDT), creates and loads core managers (UserManager, AccountManager, BillManager), and presents the login window. On successful login, opens the MainDashboard.
Lifecycle:
Run on EDT via SwingUtilities#invokeLater(Runnable).
Instantiate managers and load data from ./data folders.
Show LoginWindow and authenticate.
On success: open MainDashboard. On dashboard close: return to login.
Error handling: If data loading fails, shows an error dialog and exits.
See also
LoginWindow
MainDashboard
UserManager
AccountManager
BillManager
Member Function Documentation
main()
void com.bank.gui.app.EBankingApp.main (String[] args) static
Application entry point (Swing).
Parameters
args Command-line arguments (unused).
Sets up managers and preloads user/account/bill data; then opens the login window.
References com.bank.manager.AccountManager.load(), com.bank.manager.UserManager.load(), and com.bank.manager.BillManager.loadBills().
The documentation for this class was generated from the following file:
gui/app/EBankingApp.java