E-Banking System: com.bank.manager.BillManager Class Reference
com.bank.manager.BillManager Class Reference
Managers
Manages issuing, paying, loading and persisting bills.
Public Member Functions
BillManager (AccountManager accountManager, UserManager userManager)
Constructs the manager and loads persisted state.
void createBill (Bill bill)
Issues (creates or replaces) a bill and persists it.
void payBill (Bill bill)
Marks a bill as paid and persists updates.
void loadBills ()
Loads bills from global ledgers and daily files; rebuilds in-memory state.
void saveAll ()
Persists in-memory issued & paid lists to global ledgers.
List< Bill > getAllBills ()
Returns all bills (issued + paid).
List< Bill > getIssuedBills ()
List< Bill > getPaidBills ()
Bill getBillByRF (String rfCode)
Finds a bill by its RF/paymentCode among all bills.
Detailed Description
Manages issuing, paying, loading and persisting bills.
Coordinates Bill lifecycle and storage:
Issue bills (unique by payment code) and persist them in date-based daily files.
Mark bills as paid and persist them into a separate paid ledger.
Load bills from:
Global ledgers: issued.csv, paid.csv
Daily files: ./data/bills/YYYY-MM-DD.csv
Resolve issuer BusinessAccount via AccountManager and UserManager (by VAT).
Storage layout:
./data/bills/
  issued.csv              # open (unpaid) bills (isPaid stripped)
  paid.csv                # paid bills (isPaid:true)
  2025-10-07.csv          # daily snapshot(s)
  2025-10-08.csv          # ...
See also
Bill
AccountManager
UserManager
CsvStorageManager
Constructor & Destructor Documentation
BillManager()
com.bank.manager.BillManager.BillManager (AccountManager accountManager, UserManager userManager)
Constructs the manager and loads persisted state.
Parameters
accountManager Used to resolve issuer BusinessAccounts.
userManager Used to resolve issuer Company by VAT.
References loadBills().
Member Function Documentation
createBill()
void com.bank.manager.BillManager.createBill (Bill bill)
Issues (creates or replaces) a bill and persists it.
Ensures uniqueness by paymentCode inside in-memory issued list.
Writes/updates the entry in the daily file (by issueDate).
Strips isPaid before saving to daily file and issued ledger.
Calls saveAll() to sync global ledgers.
Parameters
bill The bill to create/update.
References com.bank.model.bills.Bill.getIssueDate(), com.bank.model.bills.Bill.getPaymentCode(), com.bank.model.bills.Bill.marshal(), and saveAll().
getAllBills()
List< Bill > com.bank.manager.BillManager.getAllBills ()
Returns all bills (issued + paid).
Returns
A new list containing all bills.
getBillByRF()
Bill com.bank.manager.BillManager.getBillByRF (String rfCode)
Finds a bill by its RF/paymentCode among all bills.
Parameters
rfCode The payment reference code.
Returns
The matching Bill or null if not found.
References getAllBills(), and com.bank.model.bills.Bill.getPaymentCode().
getIssuedBills()
List< Bill > com.bank.manager.BillManager.getIssuedBills ()
Returns
A copy of the current issued (unpaid) bills.
getPaidBills()
List< Bill > com.bank.manager.BillManager.getPaidBills ()
Returns
A copy of the current paid bills.
loadBills()
void com.bank.manager.BillManager.loadBills ()
Loads bills from global ledgers and daily files; rebuilds in-memory state.
Clears current lists.
Loads issued.csv into issuedBills (only unpaid).
Loads paid.csv into paidBills (forced paid=true).
Scans daily files and merges unseen unpaid bills into issuedBills.
Resolves issuer BusinessAccount for each bill via parseBill(String).
References com.bank.model.bills.Bill.getPaymentCode(), and com.bank.model.bills.Bill.setPaid().
payBill()
void com.bank.manager.BillManager.payBill (Bill bill)
Marks a bill as paid and persists updates.
Moves the bill from issued to paid in-memory lists.
Updates the day file entry (still stripped isPaid).
Appends to global paid.csv with isPaid:true.
Calls saveAll() to refresh global ledgers.
Parameters
bill The bill to mark as paid.
References com.bank.model.bills.Bill.getPaymentCode(), saveAll(), and com.bank.model.bills.Bill.setPaid().
saveAll()
void com.bank.manager.BillManager.saveAll ()
Persists in-memory issued & paid lists to global ledgers.
issued.csv: saves unpaid bills (without isPaid).
paid.csv: saves paid bills (with isPaid:true).
The documentation for this class was generated from the following file:
manager/BillManager.java