E-Banking System: com.bank.gui.view.panel.AdminPayBillPanel Class Reference
com.bank.gui.view.panel.AdminPayBillPanel Class Reference
Επιτρέπει σε διαχειριστή να πληρώσει λογαριασμό (Bill) εκ μέρους πελάτη.
Public Member Functions
AdminPayBillPanel (AccountManager accountManager, UserManager userManager)
Δημιουργεί το panel πληρωμής λογαριασμού από Admin.
Detailed Description
Επιτρέπει σε διαχειριστή να πληρώσει λογαριασμό (Bill) εκ μέρους πελάτη.
Ροή χρήσης:
Εισαγωγή VAT πελάτη και "Load Accounts" για φόρτωση λογαριασμών του.
Επιλογή λογαριασμού χρέωσης (IBAN) από combo box.
Εισαγωγή RF Code του λογαριασμού προς πληρωμή και "Pay".
Γίνονται έλεγχοι ύπαρξης πελάτη, υπολοίπου, ύπαρξης/κατάστασης λογαριασμού κ.λπ.
Χρησιμοποιεί:
UserManager για αναζήτηση πελάτη με VAT.
AccountManager για ανάκτηση λογαριασμών πελάτη.
BillManager για εύρεση Bill από RF code.
TransactionManager για εκτέλεση Payment.
Constructor & Destructor Documentation
AdminPayBillPanel()
com.bank.gui.view.panel.AdminPayBillPanel.AdminPayBillPanel (AccountManager accountManager, UserManager userManager)
Δημιουργεί το panel πληρωμής λογαριασμού από Admin.
Parameters
accountManager Διαχειριστής λογαριασμών.
userManager Διαχειριστής χρηστών (εύρεση πελάτη με VAT).
References com.bank.manager.TransactionManager.execute(), com.bank.manager.AccountManager.findByIban(), com.bank.manager.UserManager.findByVat(), com.bank.manager.AccountManager.getAllAccounts(), com.bank.model.bills.Bill.getAmount(), com.bank.model.accounts.Account.getBalance(), com.bank.manager.BillManager.getBillByRF(), com.bank.model.bills.Bill.getIssuer(), com.bank.manager.BillManager.loadBills(), com.bank.manager.BillManager.saveAll(), and com.bank.model.bills.Bill.setPaid().
The documentation for this class was generated from the following file:
gui/view/panel/AdminPayBillPanel.java