E-Banking System: com.bank.manager.StatementManager Class Reference
com.bank.manager.StatementManager Class Reference
Managers
Handles persistence and retrieval of account statement entries.
Public Member Functions
StatementManager ()
Creates the statement manager and ensures the base directory exists.
void saveStatement (Account acc, StatementEntry entry)
Appends a single statement entry to the account's statement file.
List< StatementEntry > load (Account acc)
Loads all statement entries for a given account.
Detailed Description
Handles persistence and retrieval of account statement entries.
Each account has a separate CSV file containing its transaction statements. The manager provides methods to:
Save new StatementEntry lines after deposits, withdrawals, transfers, or payments.
Load and reconstruct full statement history for a given Account.
Storage layout:
./data/statements/
  GR100123456789012.csv   # statement entries for account GR100123456789012
  GR200987654321098.csv   # ...
Example line (CSV):
JohnDoe,GR100...,GR200...,500.0,Transfer Payment,Credit,2025-10-07 14:32:00,1500.0
See also
StatementEntry
Account
CsvStorageManager
Constructor & Destructor Documentation
StatementManager()
com.bank.manager.StatementManager.StatementManager ()
Creates the statement manager and ensures the base directory exists.
Member Function Documentation
load()
List< StatementEntry > com.bank.manager.StatementManager.load (Account acc)
Loads all statement entries for a given account.
Reads the account’s CSV file (if it exists) and converts each line into a StatementEntry instance. The list is reversed so that the most recent entries appear first.
Parameters
acc The account whose statements to load.
Returns
A list of StatementEntry objects in reverse chronological order.
References com.bank.model.accounts.Account.getIban(), and com.bank.model.statements.StatementEntry.unmarshal().
saveStatement()
void com.bank.manager.StatementManager.saveStatement (Account acc, StatementEntry entry)
Appends a single statement entry to the account's statement file.
Automatically creates the file if it doesn’t exist.
Example:
StatementEntry entry = new StatementEntry("John", "GR100...", "GR200...", 200.0,
     "Payment of invoice 123", "Debit", LocalDateTime.now(), 800.0);
statementManager.saveStatement(account, entry);
Parameters
acc The account whose statement file to append to.
entry The StatementEntry to save.
References com.bank.model.accounts.Account.getIban().
The documentation for this class was generated from the following file:
manager/StatementManager.java