E-Banking System: com.bank.gui.view.panel.TransferPanel Class Reference
com.bank.gui.view.panel.TransferPanel Class Reference
Μεταφορά χρημάτων από λογαριασμό του χρήστη προς άλλον λογαριασμό (IBAN).
Public Member Functions
TransferPanel (User user, AccountManager accountManager)
Δημιουργεί το panel μεταφοράς χρημάτων για τον τρέχοντα χρήστη.
Detailed Description
Μεταφορά χρημάτων από λογαριασμό του χρήστη προς άλλον λογαριασμό (IBAN).
Ροή χρήσης:
Επιλογή λογαριασμού χρέωσης (From Account).
Συμπλήρωση IBAN παραλήπτη, ποσού και περιγραφής.
Κουμπί "Transfer" για εκτέλεση της συναλλαγής Transfer μέσω TransactionManager.
Το υπόλοιπο του λογαριασμού χρέωσης εμφανίζεται και ενημερώνεται δυναμικά.
Έλεγχοι:
Μη κενή περιγραφή & θετικό ποσό.
Έγκυρος παραλήπτης και διαφορετικός από τον αποστολέα.
Επαρκές υπόλοιπο.
Constructor & Destructor Documentation
TransferPanel()
com.bank.gui.view.panel.TransferPanel.TransferPanel (User user, AccountManager accountManager)
Δημιουργεί το panel μεταφοράς χρημάτων για τον τρέχοντα χρήστη.
Parameters
user Ο ενεργός χρήστης (αποστολέας).
accountManager Διαχειριστής λογαριασμών (εύρεση IBAN/υπολοίπων).
References com.bank.manager.TransactionManager.execute(), com.bank.manager.AccountManager.findByIban(), com.bank.manager.AccountManager.getAllAccounts(), com.bank.model.accounts.Account.getBalance(), and com.bank.model.accounts.Account.getIban().
The documentation for this class was generated from the following file:
gui/view/panel/TransferPanel.java