E-Banking System: com.bank.gui.view.panel.AdminAccountDetailsPanel Class Reference
com.bank.gui.view.panel.AdminAccountDetailsPanel Class Reference
Προβολή λεπτομερειών λογαριασμού για Admin.
Public Member Functions
AdminAccountDetailsPanel (AccountManager accountManager)
Δημιουργεί το panel προβολής λεπτομερειών λογαριασμού.
Detailed Description
Προβολή λεπτομερειών λογαριασμού για Admin.
Παρέχει πεδίο εισαγωγής IBAN και κουμπί "Search". Εμφανίζει IBAN, ιδιοκτήτη, υπόλοιπο, επιτόκιο, ημερομηνία δημιουργίας και τύπο λογαριασμού (Business: μηνιαία χρέωση, Personal: συνδικαιούχοι).
See also
com.bank.gui.view.MainDashboard
AccountManager
Account
BusinessAccount
PersonalAccount
Constructor & Destructor Documentation
AdminAccountDetailsPanel()
com.bank.gui.view.panel.AdminAccountDetailsPanel.AdminAccountDetailsPanel (AccountManager accountManager)
Δημιουργεί το panel προβολής λεπτομερειών λογαριασμού.
Parameters
accountManager Υπηρεσία αναζήτησης λογαριασμών (findByIban).
References com.bank.manager.AccountManager.findByIban(), com.bank.model.accounts.Account.getBalance(), com.bank.model.accounts.Account.getDateCreated(), com.bank.model.users.User.getFullName(), com.bank.model.accounts.Account.getIban(), com.bank.model.accounts.Account.getInterestRate(), com.bank.model.accounts.Account.getOwner(), and com.bank.model.users.Customer.getVat().
The documentation for this class was generated from the following file:
gui/view/panel/AdminAccountDetailsPanel.java