E-Banking System: com.bank.gui.view.panel.AdminAccountStatementsPanel Class Reference
com.bank.gui.view.panel.AdminAccountStatementsPanel Class Reference
Προβολή καταστάσεων λογαριασμού (statements) για χρήση από τον διαχειριστή.
Public Member Functions
AdminAccountStatementsPanel (AccountManager accountManager)
Δημιουργεί το panel προβολής κινήσεων λογαριασμού.
Detailed Description
Προβολή καταστάσεων λογαριασμού (statements) για χρήση από τον διαχειριστή.
Ο διαχειριστής μπορεί να επιλέξει έναν λογαριασμό από λίστα IBANs και να προβάλλει τις κινήσεις του (StatementEntries) όπως έχουν αποθηκευτεί στο σύστημα μέσω του StatementManager.
Λειτουργία:
Φορτώνει όλους τους λογαριασμούς από τον AccountManager.
Επιτρέπει επιλογή λογαριασμού μέσω JComboBox.
Με το κουμπί “Show” φορτώνει τα statements από τον StatementManager.
Εμφανίζει τις εγγραφές στο JTextArea.
See also
AccountManager
StatementManager
com.bank.model.statements.StatementEntry
Constructor & Destructor Documentation
AdminAccountStatementsPanel()
com.bank.gui.view.panel.AdminAccountStatementsPanel.AdminAccountStatementsPanel (AccountManager accountManager)
Δημιουργεί το panel προβολής κινήσεων λογαριασμού.
Parameters
accountManager Χρησιμοποιείται για φόρτωση λογαριασμών και εύρεση IBAN.
References com.bank.manager.AccountManager.findByIban(), com.bank.manager.AccountManager.getAllAccounts(), and com.bank.manager.StatementManager.load().
The documentation for this class was generated from the following file:
gui/view/panel/AdminAccountStatementsPanel.java