E-Banking System: com.bank.gui.view.panel.AdminCreateAccountPanel Class Reference
com.bank.gui.view.panel.AdminCreateAccountPanel Class Reference
Παράθυρο δημιουργίας νέου λογαριασμού από τον διαχειριστή.
Public Member Functions
AdminCreateAccountPanel (AccountManager accountManager, UserManager userManager)
Δημιουργεί το GUI panel για την εγγραφή νέου λογαριασμού.
Detailed Description
Παράθυρο δημιουργίας νέου λογαριασμού από τον διαχειριστή.
Επιτρέπει στον διαχειριστή να δημιουργεί νέους τραπεζικούς λογαριασμούς για πελάτες του συστήματος (είτε φυσικά πρόσωπα είτε εταιρείες), καθορίζοντας τον τύπο του λογαριασμού, το επιτόκιο και —για επιχειρηματικούς— το μηνιαίο πάγιο.
Λειτουργία:
Ο διαχειριστής επιλέγει τύπο λογαριασμού (Personal ή Business).
Εισάγει ΑΦΜ πελάτη και ποσοστό επιτοκίου.
Για Business accounts εισάγει επίσης μηνιαίο πάγιο.
Με την επιβεβαίωση δημιουργείται PersonalAccount ή BusinessAccount και αποθηκεύεται μέσω του AccountManager.
See also
AccountManager
UserManager
PersonalAccount
BusinessAccount
Constructor & Destructor Documentation
AdminCreateAccountPanel()
com.bank.gui.view.panel.AdminCreateAccountPanel.AdminCreateAccountPanel (AccountManager accountManager, UserManager userManager)
Δημιουργεί το GUI panel για την εγγραφή νέου λογαριασμού.
Parameters
accountManager Ο διαχειριστής λογαριασμών για δημιουργία & αποθήκευση.
userManager Ο διαχειριστής χρηστών για εύρεση του κατόχου μέσω ΑΦΜ.
References com.bank.manager.AccountManager.addAccount(), com.bank.manager.UserManager.findByVat(), com.bank.model.accounts.Account.getIban(), and com.bank.manager.AccountManager.saveAll().
The documentation for this class was generated from the following file:
gui/view/panel/AdminCreateAccountPanel.java