E-Banking System: add_doxygen_stubs Namespace Reference
add_doxygen_stubs Namespace Reference
Functions
has_doc_before (content, start_idx, lookback=3)
insert_stub (content, idx, kind, name)
process_file (pathlib.Path path)
main ()
Variables
list CLASS_PATTERNS
list FUNC_PATTERNS
Detailed Description
add_doxygen_stubs.py
--------------------
Βοηθητικό εργαλείο για να προσθέσει γρήγορα Doxygen/Javadoc stubs
σε projects με πολλές κλάσεις (C/C++/Java).
Χρήση:
    python tools/add_doxygen_stubs.py --roots src include --ext .h .hpp .c .cpp .java
Τι κάνει:
- Σαρώνει αρχεία και αν δεν βρίσκει Doxygen block πριν από κλάσεις/συναρτήσεις,
  εισάγει ένα ελάχιστο πρότυπο.
- *Ασφαλές*: κρατά backup του αρχείου(.bak) πριν την αλλαγή.
Σημ.: Είναι απλό regex-based εργαλείο, δεν καταλαβαίνει όλες τις γλωσσικές γωνίες.
Function Documentation
has_doc_before()
add_doxygen_stubs.has_doc_before (content, start_idx, lookback = 3)
Check if there is a /** ... */ doxygen block in the previous few lines.
insert_stub()
add_doxygen_stubs.insert_stub (content, idx, kind, name)
main()
add_doxygen_stubs.main ()
References main(), and process_file().
process_file()
add_doxygen_stubs.process_file (pathlib.Path path)
References has_doc_before(), and insert_stub().
Variable Documentation
CLASS_PATTERNS
list add_doxygen_stubs.CLASS_PATTERNS
Initial value:
=  [
    re.compile(r'^\s*(class|struct)\s+([A-Za-z_]\w*)', re.MULTILINE),
    re.compile(r'^\s*public\s+class\s+([A-Za-z_]\w*)', re.MULTILINE),  # Java
]
FUNC_PATTERNS
list add_doxygen_stubs.FUNC_PATTERNS
Initial value:
=  [
    # C/C++ very rough: return_type name(args) { or ;
    re.compile(r'^[^\n;{}]*?\b([A-Za-z_]\w*)\s*\‍([^;{}]*\‍)\s*(?:{|;)', re.MULTILINE),
    # Java methods (very rough)
    re.compile(r'^\s*(public|protected|private|static|\s)+[A-Za-z_<>\[\]]+\s+([A-Za-z_]\w*)\s*\‍([^;{}]*\‍)\s*(?:{|;)', re.MULTILINE),
]