E-Banking System: com.bank.model.orders.TransferOrder Class Reference
com.bank.model.orders.TransferOrder Class Reference
Standing order that transfers a fixed amount between two IBANs on a specific day each month.
Public Member Functions
TransferOrder (String title, String description, String fromIban, String toIban, double amount, int transferFreq, int transferDay, LocalDate startingDate, LocalDate endingDate)
Constructs a transfer standing order.
void execute (LocalDate trDayDate, BillManager billMan, AccountManager accountMan, TransactionManager transMan, User user)
Executes the transfer if the date matches the schedule and funds are sufficient.
boolean isFailed ()
Whether the standing order has permanently failed.
String marshal ()
Serializes this transfer order to a key-value single line.
void unmarshal (String data)
Populates this transfer order from a serialized key-value string.
Public Member Functions inherited from com.bank.model.orders.StandingOrder
StandingOrder (String title, String description, LocalDate startingDate, LocalDate endingDate)
Constructs a new standing order.
String getOrderId ()
String getTitle ()
String getDescription ()
Boolean getIsActive ()
void setIsActive (Boolean isActive)
LocalDate getStartingDate ()
LocalDate getEndingDate ()
boolean isExpired ()
Determines whether the order is expired.
Additional Inherited Members
Public Attributes inherited from com.bank.model.orders.StandingOrder
String description
Optional textual description.
Boolean isActive = true
Indicates if the order is currently active.
Protected Attributes inherited from com.bank.model.orders.StandingOrder
String orderId
Unique identifier for this order (UUID).
String title
Descriptive title of the standing order.
LocalDate startingDate
The date when this order becomes active.
LocalDate endingDate
The date when this order expires.
Static Protected Attributes inherited from com.bank.model.orders.StandingOrder
static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
Date formatter used for serialization/deserialization.
Detailed Description
Standing order that transfers a fixed amount between two IBANs on a specific day each month.
TransferOrder extends StandingOrder to automate periodic transfers. It executes on months where the execution date falls within the validity window and the day-of-month equals transferDay. On each failed attempt (e.g., insufficient balance), the failure counter increases; after more than 3 failures the order deactivates.
Notes:
transferFreq is stored/serialized but not currently enforced in execute; the implementation runs on the matching transferDay of any month within the window.
Consider validating negative amounts and adding null checks for accounts.
See also
StandingOrder
Transfer
AccountManager
TransactionManager
Constructor & Destructor Documentation
TransferOrder()
com.bank.model.orders.TransferOrder.TransferOrder (String title, String description, String fromIban, String toIban, double amount, int transferFreq, int transferDay, LocalDate startingDate, LocalDate endingDate)
Constructs a transfer standing order.
Parameters
title Order title.
description Order description.
fromIban IBAN of the source account.
toIban IBAN of the destination account.
amount Amount to transfer each time.
transferFreq Frequency in months (metadata; not enforced by execute()).
transferDay Day of month to execute.
startingDate Start (inclusive) of validity window.
endingDate End (inclusive) of validity window.
References com.bank.model.orders.StandingOrder.description, com.bank.model.orders.StandingOrder.endingDate, com.bank.model.orders.StandingOrder.startingDate, and com.bank.model.orders.StandingOrder.title.
Member Function Documentation
execute()
void com.bank.model.orders.TransferOrder.execute (LocalDate trDayDate, BillManager billMan, AccountManager accountMan, TransactionManager transMan, User user)
Executes the transfer if the date matches the schedule and funds are sufficient.
Execution conditions:
trDayDate is within startingDate and endingDate (inclusive).
trDayDate.getDayOfMonth() == transferDay.
Source account has at least amount balance.
On success, creates a Transfer transaction and executes it via TransactionManager. On failure, increments failedAttempts. After failedAttempts > 3, the order deactivates.
Parameters
trDayDate The attempted execution date.
billMan Unused here (required by signature), kept for uniformity with other orders.
accountMan Manager to resolve accounts by IBAN.
transMan Manager to execute the transfer transaction.
user The user initiating/owning the order (for auditing).
Reimplemented from com.bank.model.orders.StandingOrder.
References com.bank.manager.TransactionManager.execute(), com.bank.manager.AccountManager.findByIban(), com.bank.model.accounts.Account.getBalance(), com.bank.model.orders.StandingOrder.getEndingDate(), com.bank.model.accounts.Account.getIban(), com.bank.model.orders.StandingOrder.getStartingDate(), and com.bank.model.orders.StandingOrder.setIsActive().
isFailed()
boolean com.bank.model.orders.TransferOrder.isFailed ()
Whether the standing order has permanently failed.
Returns
true if failedAttempts > 3, else false.
Reimplemented from com.bank.model.orders.StandingOrder.
marshal()
String com.bank.model.orders.TransferOrder.marshal ()
Serializes this transfer order to a key-value single line.
Encodes: type, orderId, title, description, customer, amount, startDate, endDate,
fee, chargeAccount, creditAccount, frequencyInMonths, dayOfMonth. Dates use yyyy-MM-dd.
Returns
A string suitable for persistence.
Reimplemented from com.bank.model.orders.StandingOrder.
References com.bank.model.orders.StandingOrder.endingDate, com.bank.model.orders.StandingOrder.formatter, com.bank.model.orders.StandingOrder.getDescription(), com.bank.model.orders.StandingOrder.getOrderId(), com.bank.model.orders.StandingOrder.getTitle(), and com.bank.model.orders.StandingOrder.startingDate.
unmarshal()
void com.bank.model.orders.TransferOrder.unmarshal (String data)
Populates this transfer order from a serialized key-value string.
Parameters
data The serialized string produced by marshal().
Reimplemented from com.bank.model.orders.StandingOrder.
The documentation for this class was generated from the following file:
model/orders/TransferOrder.java