E-Banking System: com.bank.cli.Main Class Reference
com.bank.cli.Main Class Reference
CLI entry point for the banking application.
Static Public Member Functions
static void main (String[] args)
Application entry point.
Detailed Description
CLI entry point for the banking application.
Bootstraps managers, loads persisted data, performs interactive login and routes the logged-in user to the appropriate role-specific menu:
Individual → IndividualMenu
Company → CompanyMenu
Admin → AdminMenu
Lifecycle:
Load users, accounts, and bills from storage.
Prompt for credentials and authenticate.
Dispatch to role menu and run the CLI loop.
On exit, persist updated users & accounts.
Note
Τα IndividualMenu, CompanyMenu, AdminMenu θεωρούνται διαθέσιμα στο ίδιο project (παρέχουν τα αντίστοιχα CLI flows).
See also
UserManager
AccountManager
BillManager
TransactionManager
StatementManager
StandingOrderManager
Individual
Company
Admin
Member Function Documentation
main()
void com.bank.cli.Main.main (String[] args) static
Application entry point.
Parameters
args Command-line arguments (unused).
References com.bank.cli.AdminMenu.run(), com.bank.cli.CompanyMenu.run(), and com.bank.cli.IndividualMenu.run().
The documentation for this class was generated from the following file:
cli/Main.java